[package]
name = "authcraft"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.88"
bcrypt = "0.17.0"
chrono = "0.4.40"
jsonwebtoken = "9.3.1"
serde = { version = "1.0.219", features = ["derive"] }
